wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.0
    cli_version: 0.16.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711571173.0
    t:
      1:
      - 1
      - 55
      3:
      - 23
      4: 3.10.0
      5: 0.16.5
      8:
      - 3
      - 5
      13: windows-amd64
